name: front-end technology talk
url: http://www.fettblog.eu
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: /blog/page/:num
author:
  name: Stefan Baumgartner
  email: sbaumg@gmail.com
gems:
- jekyll-sitemap