name: front-end technology talk
url: http://www.fettblog.eu
markdown: kramdown
redcarpet:
  extensions: ["strikethrough"]
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: /blog/page/:num
author:
  name: Stefan Baumgartner
  email: sbaumg@gmail.com
sass:
  sass_dir: _sass/
  style: compressed
gems:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-paginate

collections:
  snippets:
    output: true
    permalink: snippets/:title/
defaults:
  -
    scope:
      type: "snippets"
    values:
      layout: "snippet"
