name: front-end technology talk
url: http://www.fettblog.eu
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
pygments: true
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: /blog/page/:num